export const CAPABILITIES = [
  'session.view',
  'scope.switch',
  'home.view',
  'route.view',
  'route.assign',
  'route.confirm_arrival',
  'route.reconcile_load',
  'route.confirm_exit',
  'package.view',
  'package.reconcile',
  'package.return',
  'tower.view',
  'supervision.view',
  'alert.view',
  'alert.manage',
  'alert.resolve',
  'driver.contact',
  'unit.block_operational',
  'assignment.exception.change',
  'fleet.view',
  'fleet.manage',
  'maintenance.view',
  'maintenance.request',
  'maintenance.manage',
  'fuel.view',
  'fuel.authorize',
  'expense.view',
  'expense.capture',
  'expense.reconcile',
  'talent.view',
  'talent.incident.capture',
  'payroll.incident.view',
  'settlement.view',
  'settlement.prepare',
  'settlement.confirm_liquidatable',
  'settlement.force_liquidatable',
  'billing.view',
  'invoice.approve',
  'report.view',
  'management.view',
  'pnl.view',
  'copilot.view',
  'approval.inbox',
  'csc.view',
  'csc.prepare',
  'csc.tenant.switch',
  'support.view',
  'audit.view',
  'config.view',
] as const

export type Capability = (typeof CAPABILITIES)[number]

export const PROFILES = [
  'dispatcher',
  'supervisor',
  'fleet_coordinator',
  'admin_finance',
  'manager',
  'csc_operator',
  'platform_admin',
] as const

export type Profile = (typeof PROFILES)[number]

export const PROFILE_LABELS: Record<Profile, string> = {
  dispatcher: 'Despachador CEDIS',
  supervisor: 'Supervisor operativo',
  fleet_coordinator: 'Coordinador de flota',
  admin_finance: 'Administrador de operaciones',
  manager: 'Gerente / propietario',
  csc_operator: 'Operador CSC Vía Ágil',
  platform_admin: 'Administrador de plataforma',
}

const BASE: Capability[] = ['session.view', 'scope.switch', 'home.view']

export const PROFILE_CAPABILITIES: Record<Profile, readonly Capability[]> = {
  dispatcher: [
    ...BASE,
    'route.view',
    'route.assign',
    'route.confirm_arrival',
    'route.reconcile_load',
    'route.confirm_exit',
    'package.view',
    'package.reconcile',
    'package.return',
    'tower.view',
    'alert.view',
  ],
  supervisor: [
    ...BASE,
    'route.view',
    'package.view',
    'tower.view',
    'supervision.view',
    'alert.view',
    'alert.manage',
    'alert.resolve',
    'driver.contact',
    'unit.block_operational',
    'assignment.exception.change',
    'fleet.view',
    'maintenance.view',
    'maintenance.request',
    'talent.view',
    'talent.incident.capture',
  ],
  fleet_coordinator: [
    ...BASE,
    'route.view',
    'tower.view',
    'fleet.view',
    'fleet.manage',
    'maintenance.view',
    'maintenance.request',
    'maintenance.manage',
    'fuel.view',
    'alert.view',
  ],
  admin_finance: [
    ...BASE,
    'route.view',
    'package.view',
    'fleet.view',
    'maintenance.view',
    'fuel.view',
    'fuel.authorize',
    'expense.view',
    'expense.capture',
    'expense.reconcile',
    'talent.view',
    'talent.incident.capture',
    'payroll.incident.view',
    'settlement.view',
    'settlement.prepare',
    'settlement.confirm_liquidatable',
    'billing.view',
    'report.view',
    'approval.inbox',
  ],
  manager: [
    ...BASE,
    'route.view',
    'package.view',
    'tower.view',
    'fleet.view',
    'maintenance.view',
    'fuel.view',
    'talent.view',
    'settlement.view',
    'billing.view',
    'report.view',
    'management.view',
    'pnl.view',
    'copilot.view',
    'approval.inbox',
    'audit.view',
  ],
  csc_operator: [
    ...BASE,
    'route.view',
    'package.view',
    'tower.view',
    'fleet.view',
    'maintenance.view',
    'fuel.view',
    'expense.view',
    'talent.view',
    'payroll.incident.view',
    'settlement.view',
    'settlement.prepare',
    'billing.view',
    'report.view',
    'csc.view',
    'csc.prepare',
    'csc.tenant.switch',
    'support.view',
    'audit.view',
    'config.view',
  ],
  platform_admin: [
    ...BASE,
    'route.view',
    'package.view',
    'tower.view',
    'fleet.view',
    'maintenance.view',
    'fuel.view',
    'expense.view',
    'talent.view',
    'settlement.view',
    'billing.view',
    'report.view',
    'management.view',
    'support.view',
    'audit.view',
    'config.view',
  ],
}

export function capabilitiesFor(profile: Profile): Capability[] {
  return [...PROFILE_CAPABILITIES[profile]]
}
